### ISSUE TITLE
how to use proxy?

### ISSUE THREAD

**Issue by philos3** [dart-lang/web_socket_channel#86]
how to use proxy?
such as wss://api.huobi.pro/ws  can't connect in china,we must use proxy

**Comment by aswanthtpc** [comment]
got any solution ?

**Comment by shkvoretz** [comment]
we need this also.

**Comment by dudeofawesome** [comment]
There are 2 open PRs to add this: #215 & #211 on `IOWebSocketChannel`s. If you need this now, you can add a dependency pointing to one of those forks:

```yaml
  web_socket_channel:
    git:
      url: git@github.com:iunu/web_socket_channel.git
      ref: feat/custom-client
```
